sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.17.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo docker network create nsa
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d --build

script:
  - echo "Hi from Travis"

after_script:
  - docker-compose down -v
